package com.bear.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import com.bear.entity.User;
import com.bear.entity.UserExample;

@Component("userMapper")
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Sun May 14 00:48:43 CST 2017
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Sun May 14 00:48:43 CST 2017
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Sun May 14 00:48:43 CST 2017
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Sun May 14 00:48:43 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Sun May 14 00:48:43 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Sun May 14 00:48:43 CST 2017
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Sun May 14 00:48:43 CST 2017
     */
    User selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Sun May 14 00:48:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Sun May 14 00:48:43 CST 2017
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Sun May 14 00:48:43 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Sun May 14 00:48:43 CST 2017
     */
    int updateByPrimaryKey(User record);
}